config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  root :to => 'session#new'
  resources :reservations
  resources :flights
  resources :airplanes
  resources :users, :only => [:new, :create]

  get '/user' => 'users#show'


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id          :bigint(8)        not null, primary key
#  date        :text
#  to          :text
#  from        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  airplane_id :text
#

class Flight < ApplicationRecord
  belongs_to :airplane
  
  has_many :reservations
  has_many :users, :through => :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  before_action :check_for_login, only: [:new, :edit]
  before_action :check_for_admin, only: [:new, :edit, :create ]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    @user = session[:user_id]
    @username = session[:username]


  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @seats = @flight.reservations #shows all the seats available
    @users = User.all
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        seats = Flight.last.airplane.rows.to_i * Flight.last.airplane.cols.to_i #this works out how many seats are going to be on this flight

        (1..seats).map do |n|
          reservation = Reservation.new 
          reservation.flight_id = Flight.last.id
          reservation.username = "empty"
          reservation.save
      end

        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:date, :to, :from, :airplane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_area :date %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_area :from %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_area :to %>
  </div>



  <div class="field">
  <%= form.select :airplane_id, Airplane.pluck(:name, :id), :include_blank => true  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>




<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>
<div class="grid-container">
<h1>Flights</h1>
<div class="grid-item">
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>To</th>
      <th>From</th>
      <th>Aircraft</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.date %></td>
        <td><%= flight.to %></td>
        <td><%= flight.from %></td>
        <td><%= flight.airplane.name %></td>
        <td><%= link_to 'Show', flight, :class=>"table-link" %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight), :class=>"table-link" %></td>
        <td><%= link_to 'Destroy', flight, :method=>"delete", data: { confirm: 'Are you sure?' }, :class=>"table-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<%= link_to 'New Flight', new_flight_path, :class=>"link" %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p class="booking-info">
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p class="booking-info">
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p class="booking-info">
  <strong>To:</strong>
  <%= @flight.to %>
</p>

<div class="seat-container">
<% @seats.each_with_index do |seat, index | %>

<div class="seat">
  <h4>Seat: <%= index + 1 %></h4>

  <h4>  </h4>
  </div>

<% end %>
</div>


<div class="control">
<%= link_to 'Edit', edit_flight_path(@flight), :class=>"link" %> |
<%= link_to 'Back', flights_path, :class=>"link" %>
</div>