config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  root :to => 'session#new'
  resources :reservations
  resources :flights
  resources :airplanes
  resources :users, :only => [:new, :create]

  get '/user' => 'users#show'


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/airplane.rb
# == Schema Information
#
# Table name: airplanes
#
#  id         :bigint(8)        not null, primary key
#  rows       :text
#  cols       :text
#  name       :text
#  bonus      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airplane < ApplicationRecord
  has_many :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]
  before_action :check_for_login, only: [:new, :edit]
  before_action :check_for_admin

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)
    
    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:rows, :cols, :name, :bonus)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<div class="grid-container">
<%= form_with(model: airplane, local: true) do |form| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rows %>
    <%= form.text_area :rows %>
  </div>

  <div class="field">
    <%= form.label :cols %>
    <%= form.text_area :cols %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table>
  <thead>
    <tr>
      <th>Rows</th>
      <th>Cols</th>
      <th>Name</th>
      <th>Bonus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airplanes.each do |airplane| %>
      <tr>
        <td><%= airplane.rows %></td>
        <td><%= airplane.cols %></td>
        <td><%= airplane.name %></td>
        <td><%= airplane.bonus %></td>
        <td><%= link_to 'Show', airplane, :class=>"table-link" %></td>
        <td><%= link_to 'Edit', edit_airplane_path(airplane), :class=>"table-link" %></td>
        <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"table-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

<%= link_to 'New Airplane', new_airplane_path, :class=>"link" %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>
<br><br>
<%= link_to 'Back', airplanes_path, :class=>"link back-link" %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rows:</strong>
  <%= @airplane.rows %>
</p>

<p>
  <strong>Cols:</strong>
  <%= @airplane.cols %>
</p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Bonus:</strong>
  <%= @airplane.bonus %>
</p>
<%= link_to 'Add a Flight', new_flight_path(@airplane) %> |
<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>